apiVersion: v1
kind: Service
metadata: 
 name: Dev-Clus-svr
spec: 
 selectot: 
  Env: dev
  Project: roboshop
  Compenent: nginx
 ports:
  #- name: ingre-http
  - protocal: TCP
    port: 80
    targetPort: 80
     