apiVersion: v1
kind: Service
metadata: 
 name: dev-clus-svr
spec: 
 selector: 
  Env: dev
  Project: roboshop
  Compenent: nginx
 ports:
  -  protocol: TCP
     name: ingress-http  
     port: 80
     targetPort: 80
     