apiVersion: v1
kind: Service
metadata: 
 name: dev-clus-svr
spec: 
 selector: 
  Env: dev
  Project: roboshop
  Compenent: nginx
 ports:
  -  protocol: TCP
     name: ingress-http  
     port: 80
     targetPort: 80
     

---
apiVersion: v1
kind: Service 
metadata: 
 name: dev-np-svc 
spec: 
 type: NodePort
 selector: 
  Env: dev
  Project: roboshop
  Compenent: nginx
 ports: 
  - protocol: TCP 
    port: 8080
    targetPort: 80

---
apiVersion: v1 
kind: Service 
metadata: 
 name: dev-lb-svc 
spec: 
 selector: 
  Env: dev
  Project: roboshop
  Compenent: nginx 
 type: LoadBalancer
 ports: 
  - protocol: TCP
    port: 80
    targetPort: 30006

---
apiVersion: v1 
kind: Service 
metadata: 
 name: ora-db-sl 
spec: 
 ports:
 - protocol: TCP 
   port: 1521
   targetPort: 1521
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ora-db-sl   # must match the Service name
subsets:
  - addresses:
      - ip: 210.14.149.5   # IP of the external database
    ports:
      - port: 1521          # port on the external database
